# Copyright (c) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
# Adapted from https://docs.habana.ai/en/latest/Orchestration/HabanaAI_Operator/Deploying_HabanaAI_Operator.html#using-cli
#
---
apiVersion: v1
kind: Namespace
metadata:
   name: habana-ai-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
   name: habana-ai-operator
   namespace: habana-ai-operator
spec:
   targetNamespaces:
   - habana-ai-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
   name: habana-ai-operator
   namespace: habana-ai-operator
spec:
   channel: stable
   installPlanApproval: Automatic
   name: habana-ai-operator
   source: certified-operators
   sourceNamespace: openshift-marketplace