# Copyright (c) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: intel-dsa
  namespace: intel-dsa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: intel-dsa
  namespace: intel-dsa
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - intel-dsa-scc
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: intel-dsa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: intel-dsa
subjects:
- kind: ServiceAccount
  name: intel-dsa
  namespace: intel-dsa