# Copyright (c) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opea-chatqna
  namespace: opea-chatqna
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opea-chatqna
  namespace: opea-chatqna
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - anyuid
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opea-chatqna
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: opea-chatqna
subjects:
- kind: ServiceAccount
  name: opea-chatqna
  namespace: opea-chatqna
---
# Redis Vector DB deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-vector-db
  namespace: opea-chatqna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-vector-db
  template:
    metadata:
      labels:
        app: redis-vector-db
    spec:
      serviceAccount: opea-chatqna
      containers:
      - name: redis-vector-db
        image: redis/redis-stack:7.2.0-v9
        ports:
        - containerPort: 6379
        - containerPort: 8001
---
# Redis Vector DB Service
apiVersion: v1
kind: Service
metadata:
  name: redis-vector-db
  namespace: opea-chatqna
spec:
  type: ClusterIP
  selector:
    app: redis-vector-db
  ports:
  - name: redis-service
    port: 6379
    targetPort: 6379
  - name: redis-insight
    port: 8001
    targetPort: 8001