# Copyright (c) 2022 - 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 100-intel-iommu-on
spec:
  config:
    ignition:
      version: 3.2.0
  kernelArguments:
      - intel_iommu=on,sm_on modules_load=vfio-pci vfio-pci.ids=8086:4941,8086:4943
  selector:
    intel.feature.node.kubernetes.io/qat: 'true'
    intel.feature.node.kubernetes.io/dsa: 'true'
